import axios from 'axios';
import Head from "next/head";
import Image from "next/image";
import { useState } from 'react';
import { useRouter } from "next/router";

import styles from "../styles/Home.module.css";

export default function Home() { 
  // variable state
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const router = useRouter();

  const Auth = async(e) =>{
    e.preventDefault();
    try {
      await axios.post('http://localhost:5000/api/user/login',
      {
        username: username,
        password: password
      },{
        withCredentials: true
      });
      router.push('/chat-app')
    } catch (error) {
      console.log(error);
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
        <h1 className={styles.title}>
          Welcome to <span>Chat App</span>
        </h1>
        </div>
        {/* inputan username and password */}
        <form onSubmit={Auth} method="post">
          <input type="text" name="username" id="username" onChange={(e) => setUsername(e.target.value)} />
          <input type="password"  name="password" id="password" onChange={(e) => setPassword(e.target.value)}/>
          <button type='submit'>Masuk</button>
        </form>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
